namespace ArtificialFlash
{
    [default_interface]
    runtimeclass HomeViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        HomeViewModel();
        Int32 DatasetCount;
        Int32 ModelCount;
        Boolean IsTrainingActive;
        String BackendStatus;
    }
}
