namespace ArtificialFlash
{
    [default_interface]
    runtimeclass ModelsViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ModelsViewModel();
        Windows.Foundation.Collections.IVector<IInspectable> Models { get; };
        void Refresh();
        void CreateModel(String name, String type);
        void DeleteModel(String id);
    }
}
