namespace ArtificialFlash
{
    [default_interface]
    runtimeclass TrainingChart : Microsoft.UI.Xaml.Controls.Control
    {
        TrainingChart();
        Windows.Foundation.Collections.IVector<Double> LossValues;
        Windows.Foundation.Collections.IVector<Double> AccuracyValues;
    }
}
